export type KnowledgeRecord = {
  id: string;
  title: string;
  category: string;
  content: string;
  url: string;
  keywords?: string[];
  fetchedAt?: string;
};

const site = "https://moovmoney.ga";

export const officialPages = [
  `${site}/`,
  `${site}/devenir-client/`,
  `${site}/services-de-base/`,
  `${site}/services/transfert-national/`,
  `${site}/services/depot/`,
  `${site}/services/retrait/`,
  `${site}/services/recharges/`,
  `${site}/services/achat-de-forfait/`,
  `${site}/services/paiement-seeg-et-edan/`,
  `${site}/services/facture-gabon-telecom/`,
  `${site}/services/canal-et-satcon/`,
  `${site}/services/campus-france/`,
  `${site}/moov-money-online-client/`,
  `${site}/payxpress-client/`,
  `${site}/marchand/standards-et-partenaires/`,
  `${site}/services/interoperabilite-gimacpay/`,
  `${site}/services/transfert-international/`,
  `${site}/services/remittence-entrante/`,
  `${site}/services/moov-money-banking/`,
  `${site}/moov-money-uba/`,
  `${site}/carte-visa-uba-moov-money/`,
  `${site}/devenir-marchand/`,
  `${site}/devenir-revendeur/`,
  `${site}/services/devenir-revendeur-plus/`,
  `${site}/grille-tarifaire-client/`,
  `${site}/contact/`,
] as const;

export const knowledgeSeed: KnowledgeRecord[] = [
  {
    id: "account-opening",
    title: "Ouvrir et activer un compte Moov Money",
    category: "Compte",
    content: "Un client peut ouvrir ou activer son compte Moov Money en ligne, en agence ou auprès d’un distributeur agréé. La SIM doit être identifiée au nom du client et une pièce d’identité peut être demandée. Après réception d’un mot de passe temporaire, le client compose *555# pour le remplacer par un code confidentiel. Le code PIN ne doit jamais être communiqué à un agent, à un chatbot ou à un tiers.",
    url: `${site}/devenir-client/`,
    keywords: ["ouvrir", "créer", "activer", "compte", "inscription", "pin", "mot de passe"],
  },
  {
    id: "national-transfer",
    title: "Transfert national",
    category: "Transfert",
    content: "Pour envoyer de l’argent au Gabon, ouvrez *555# ou l’application Moov Money, choisissez Transfert, renseignez le numéro du bénéficiaire et le montant, vérifiez le récapitulatif puis confirmez avec le code PIN. Le plafond public annoncé est de 1 000 000 FCFA par opération. Une transaction ne doit jamais être répétée si son statut est encore en traitement.",
    url: `${site}/services/transfert-national/`,
    keywords: ["envoyer", "transfert", "argent", "bénéficiaire", "plafond"],
  },
  {
    id: "deposit",
    title: "Dépôt d’espèces",
    category: "Dépôt",
    content: "Le dépôt permet de convertir des espèces en unités de valeur Moov Money auprès d’un agent, d’une agence ou d’un kiosque agréé. Le dépôt est annoncé gratuit dans la grille tarifaire publique. Le client doit vérifier le SMS de confirmation et le solde avant de quitter le point de vente.",
    url: `${site}/services/depot/`,
    keywords: ["dépôt", "déposer", "espèces", "agent", "gratuit"],
  },
  {
    id: "withdrawal",
    title: "Retrait d’espèces et frais",
    category: "Retrait",
    content: "Le retrait se réalise chez un agent ou revendeur via *555# ou l’application. Le client choisit Retrait, saisit le code agent et le montant puis confirme avec son PIN. Les frais publics sont de 3 % jusqu’à 160 000 FCFA, puis 5 000 FCFA pour les tranches publiées au-delà. Le retrait maximal public est de 500 000 FCFA par opération.",
    url: `${site}/services/retrait/`,
    keywords: ["retrait", "retirer", "cash", "frais", "agent", "500000"],
  },
  {
    id: "airtime",
    title: "Achat de crédit téléphonique",
    category: "Télécom",
    content: "Le client peut acheter du crédit pour son propre numéro ou pour un tiers depuis *555# ou l’application. Il choisit Achat de crédit, indique le bénéficiaire, saisit le montant et confirme. L’achat de crédit est annoncé gratuit dans la grille publique.",
    url: `${site}/services/recharges/`,
    keywords: ["recharge", "crédit", "airtime", "téléphone", "tiers"],
  },
  {
    id: "bundles",
    title: "Forfaits data et voix",
    category: "Télécom",
    content: "Les forfaits sont accessibles via *555*4#, l’application MyMoov ou l’e-catalogue. Pass data publics: 200 MB à 100 FCFA pour 1 heure; 1 GB à 500 FCFA pour 1 jour; 2 GB à 1 000 FCFA pour 3 jours; 5 GB à 2 000 FCFA pour 7 jours; 14 GB à 5 000 FCFA pour 14 jours; 30 GB à 10 000 FCFA pour 30 jours. Pass voix publics: 30 minutes à 100 FCFA pour 1 heure; 90 minutes à 500 FCFA pour 1 jour; 3 heures à 1 000 FCFA pour 3 jours; 6 heures à 2 000 FCFA pour 7 jours; 16 heures à 5 000 FCFA pour 14 jours; 40 heures à 10 000 FCFA pour 30 jours.",
    url: `${site}/services/achat-de-forfait/`,
    keywords: ["forfait", "internet", "data", "go", "gb", "voix", "minutes", "pass"],
  },
  {
    id: "seeg",
    title: "Paiement SEEG et unités EDAN",
    category: "Factures",
    content: "Le paiement SEEG et l’achat d’unités MobileDan/EDAN sont disponibles via *555*6# ou l’application. Le client sélectionne le service, renseigne la référence ou le compteur, vérifie le montant puis confirme avec son PIN. La grille publique affiche 500 FCFA pour le paiement d’une facture SEEG et 100 FCFA pour l’achat d’unités MobileDan.",
    url: `${site}/services/paiement-seeg-et-edan/`,
    keywords: ["seeg", "edan", "mobiledan", "électricité", "eau", "facture", "compteur"],
  },
  {
    id: "gabon-telecom",
    title: "Paiement Gabon Telecom",
    category: "Factures",
    content: "Moov Money permet de payer les offres ADSL, DUO et Fibre de Gabon Telecom. Depuis *555# ou l’application, choisissez Paiement, Gabon Telecom, le type de service, saisissez le numéro fixe ou la référence puis confirmez avec le PIN.",
    url: `${site}/services/facture-gabon-telecom/`,
    keywords: ["gabon telecom", "fibre", "adsl", "duo", "internet", "facture"],
  },
  {
    id: "tv",
    title: "Réabonnement Canal+ et SATCON",
    category: "Télévision",
    content: "Le réabonnement Canal+ et SATCON est disponible via *555*5# ou l’application. Le client choisit le fournisseur, renseigne le numéro de carte ou d’abonné, sélectionne la formule et confirme. La grille tarifaire publique annonce le service gratuit.",
    url: `${site}/services/canal-et-satcon/`,
    keywords: ["canal", "canal+", "satcon", "tv", "abonnement", "réabonnement"],
  },
  {
    id: "campus-france",
    title: "Paiement Campus France",
    category: "Éducation",
    content: "Le paiement Campus France se fait depuis le menu Paiement avec le numéro de dossier. La page du service annonce 80 000 FCFA de frais de dossier et une validation pouvant prendre jusqu’à 72 heures. Une incohérence existe sur les frais de service: 450 FCFA sur la page Campus France et 350 FCFA dans la grille tarifaire. Le client doit demander confirmation à Moov Money avant le paiement.",
    url: `${site}/services/campus-france/`,
    keywords: ["campus france", "études", "dossier", "80000", "350", "450"],
  },
  {
    id: "online-payment",
    title: "Moov Money Online",
    category: "Paiement",
    content: "Moov Money Online permet de payer sur un site marchand partenaire. Le client choisit Moov Money au moment du paiement, renseigne son numéro, reçoit une demande de confirmation et valide avec son PIN. La livraison et les conditions commerciales restent sous la responsabilité du marchand.",
    url: `${site}/moov-money-online-client/`,
    keywords: ["online", "internet", "site marchand", "paiement en ligne", "commande"],
  },
  {
    id: "payxpress",
    title: "Paiement PayXpress",
    category: "Paiement",
    content: "Avec PayXpress, le marchand initie la demande de paiement et le client la confirme sur son téléphone avec son PIN. Le client n’a pas besoin de composer *555#. Il doit vérifier le nom du marchand et le montant avant validation.",
    url: `${site}/payxpress-client/`,
    keywords: ["payxpress", "marchand", "demande de paiement", "sans ussd"],
  },
  {
    id: "merchant-payment",
    title: "Paiement marchand standard",
    category: "Paiement",
    content: "Pour payer un marchand standard, choisissez Paiement puis Marchand dans *555# ou l’application, saisissez le code marchand, le montant, vérifiez les informations et confirmez avec le PIN.",
    url: `${site}/marchand/standards-et-partenaires/`,
    keywords: ["payer marchand", "code marchand", "commerce", "boutique"],
  },
  {
    id: "gimac-transfer",
    title: "Transfert international CEMAC avec GIMACPAY",
    category: "International",
    content: "GIMACPAY permet des transferts vers des opérateurs membres au Gabon, Cameroun, Congo, Tchad, République centrafricaine et Guinée équatoriale. Dans le menu GIMACPAY, choisissez Transfert CEMAC, le pays, l’opérateur, le numéro, le montant puis confirmez avec le PIN. Les tarifs et disponibilités doivent être vérifiés avant l’exécution.",
    url: `${site}/services/transfert-international/`,
    keywords: ["cameroun", "congo", "tchad", "centrafrique", "guinée équatoriale", "cemac", "gimac", "international"],
  },
  {
    id: "remittance",
    title: "Réception d’argent depuis l’étranger",
    category: "International",
    content: "La rémittence entrante permet de recevoir automatiquement des fonds depuis des partenaires internationaux compatibles, notamment via TERRAPAY et des partenaires MFSA. La réception est annoncée gratuite pour le bénéficiaire. Le compte Moov Money doit être actif et le numéro transmis à l’expéditeur doit être correct.",
    url: `${site}/services/remittence-entrante/`,
    keywords: ["étranger", "recevoir", "remittance", "worldremit", "moneygram", "terrapay"],
  },
  {
    id: "uba-banking",
    title: "Moov Money Banking avec UBA",
    category: "Banking",
    content: "Le wallet peut être rattaché à un compte ou une carte UBA appartenant au même titulaire. L’enrôlement se fait en agence ou via le parcours UBA prévu. Le transfert Moov Money vers UBA coûte 3 % de 1 000 à 160 000 FCFA, puis 5 000 FCFA jusqu’à 500 000 FCFA selon la grille publique. Le transfert UBA vers Moov Money coûte 500 FCFA. La consultation du solde ou de l’historique UBA est affichée à 100 FCFA.",
    url: `${site}/moov-money-uba/`,
    keywords: ["uba", "banque", "banking", "compte bancaire", "solde uba"],
  },
  {
    id: "visa-card",
    title: "Carte Visa UBA Moov Money",
    category: "Carte",
    content: "La carte Visa UBA Moov Money est une carte prépayée liée au wallet, accessible depuis *555*8*1#. Le rechargement wallet vers carte est annoncé à 1,5 %. Le retrait sur un GAB UBA est annoncé gratuit. Les achats internet internationaux ou TPE hors UBA sont affichés à 4,5 %. Le client doit toujours vérifier les frais actualisés avant une opération internationale.",
    url: `${site}/carte-visa-uba-moov-money/`,
    keywords: ["visa", "carte", "uba", "gab", "internet international"],
  },
  {
    id: "bgfi-withdrawal",
    title: "Retrait sans carte BGFIBank",
    category: "Banking",
    content: "Moov Money Banking permet un retrait sans carte dans le réseau de GAB BGFIBank. Les frais publics sont de 3 % de 5 000 à 165 000 FCFA puis 5 000 FCFA au-delà. Le parcours exige une confirmation sécurisée et le code de retrait doit rester secret.",
    url: `${site}/services/moov-money-banking/`,
    keywords: ["bgfi", "gab", "retrait sans carte", "distributeur"],
  },
  {
    id: "merchant-onboarding",
    title: "Devenir marchand Moov Money",
    category: "Marchand",
    content: "Un commerce peut devenir marchand standard, Moov Money Online ou PayXpress. Le parcours implique une prise de contact commerciale, une SIM marchande, un dossier contractuel et, pour les services digitaux, une intégration technique. Aucun identifiant de production ne doit être placé dans le code source public.",
    url: `${site}/devenir-marchand/`,
    keywords: ["devenir marchand", "commerce", "api", "intégration", "online", "payxpress"],
  },
  {
    id: "reseller",
    title: "Devenir revendeur et Revendeur Plus",
    category: "Revendeur",
    content: "Pour devenir revendeur, il faut généralement fournir une pièce d’identité, la fiche circuit de l’activité, signer le contrat et effectuer le dépôt demandé. Revendeur Plus offre une facilité d’approvisionnement en unités de valeur pouvant atteindre 500 000 FCFA selon l’éligibilité et l’activité. Le code public indiqué pour ce service est *650#.",
    url: `${site}/devenir-revendeur/`,
    keywords: ["revendeur", "agent", "revendeur plus", "uv", "650"],
  },
  {
    id: "limits",
    title: "Plafonds publics du compte",
    category: "Plafonds",
    content: "La grille publique indique: solde maximal 5 000 000 FCFA; retrait maximal 500 000 FCFA par opération; transfert maximal 1 000 000 FCFA par opération; paiement marchand maximal 1 000 000 FCFA par opération; dépôt espèces maximal 2 000 000 FCFA par jour; total retrait, transfert et paiement: 3 000 000 FCFA par jour, 5 000 000 FCFA par semaine et 10 000 000 FCFA par mois.",
    url: `${site}/grille-tarifaire-client/`,
    keywords: ["plafond", "limite", "maximum", "par jour", "par mois", "solde maximum"],
  },
  {
    id: "security",
    title: "Sécurité du compte et du PIN",
    category: "Sécurité",
    content: "Moov Assist ne demande, ne stocke et ne transmet jamais le code PIN ni une donnée biométrique. La biométrie est vérifiée localement par WebAuthn/passkey. En cas de PIN bloqué, de SIM perdue, de téléphone volé, de transfert non reconnu ou de comportement inhabituel, le client doit interrompre les opérations et lancer un diagnostic ou contacter un conseiller.",
    url: `${site}/contact/`,
    keywords: ["sécurité", "pin bloqué", "vol", "fraude", "sim perdue", "biométrie"],
  },
  {
    id: "support",
    title: "Contacter le support Moov Money",
    category: "Support",
    content: "Le site public affiche le téléphone +241 11 79 22 00 et l’adresse contact@moovmoney.ga dans son pied de page. Une autre adresse, contact@moov-africa.ga, apparaît sur la page Contact. Pour une opération financière, utilisez de préférence l’application, le numéro officiel ou une agence et ne transmettez jamais votre PIN par e-mail.",
    url: `${site}/contact/`,
    keywords: ["support", "contact", "conseiller", "téléphone", "email", "réclamation"],
  },
];
